/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.69
 * Generated at: 2025-03-25 03:35:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.shop;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class view_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/dev/workspace/port/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/shop/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1735616831101L));
    _jspx_dependants.put("jar:file:/C:/dev/workspace/port/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/shop/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/header.jsp", out, false);
      out.write("\r\n");
      out.write("	<div class=\"container-fluid\">\r\n");
      out.write("    	<div class=\"row\">\r\n");
      out.write("			<div class=\"col-md-12\">\r\n");
      out.write("				<form role=\"form\">\r\n");
      out.write("					<input type=\"hidden\" name=\"gdsNum\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${view.gdsNum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("                    <!-- 익스프레션 자바 표현식 el 익스프레션 랭귀지 -->\r\n");
      out.write("                </form>\r\n");
      out.write("	            <div class=\"my-3\">\r\n");
      out.write("		            <div class=\"id__ContentsBox-cpafkd-3 id__ContentsTabGroup-cpafkd-4 cXkYhn gMsSet\">\r\n");
      out.write("		               <div class=\"id__Tabs-cpafkd-7 jEZriM\">\r\n");
      out.write("		                  <ul>\r\n");
      out.write("		                     <li class=\"active\">\r\n");
      out.write("		                    	<button type=\"button\">에피소드</button>\r\n");
      out.write("		                     </li>\r\n");
      out.write("		                     <li class=\"\">\r\n");
      out.write("		                     	<button type=\"button\">리뷰(0)</button> \r\n");
      out.write("		                     </li>\r\n");
      out.write("		                     <li class=\"\">\r\n");
      out.write("		                     	<button type=\"button\">프로그램 소개</button>\r\n");
      out.write("		                     </li>\r\n");
      out.write("		                     <li class=\"\">\r\n");
      out.write("		                     	<button type=\"button\">공식이미지</button>\r\n");
      out.write("		                     </li>\r\n");
      out.write("		                  </ul>\r\n");
      out.write("		              	</div>\r\n");
      out.write("	                  	<div class=>\r\n");
      out.write("	                  		<a href=\"https://www.youtube.com/watch?v=HyU3XL2F9GE&t=1s\">\r\n");
      out.write("	                  			<div class=\"\">\r\n");
      out.write("	                  				<img src=\"https://img.youtube.com/vi/HyU3XL2F9GE/0.jpg\" alt=\"휴먼 맛큐멘터리 오모우마이 가게 ~놀랍도록 후해서 재밌는 식당~\" loading=\"lazy\"/>\r\n");
      out.write("	                  			</div>\r\n");
      out.write("	                  		\r\n");
      out.write("		                  		<div class=\"info text-white my-3\">\r\n");
      out.write("		                  			<p class=\"TextBox__Txt-sc-9zsjb2-1 jccqkt subject\">Python超入門コース 合併版｜Pythonの超基本的な部分をたった1時間で学べます【プログラミング初心者向け入門講座】</p>\r\n");
      out.write("					                <p class=\"TextBox__Txt-sc-9zsjb2-1 dEnfO subject\">예고편</p>\r\n");
      out.write("					                <span class=\"date\">2020.3.20</span>\r\n");
      out.write("					            </div>\r\n");
      out.write("					         </a>  \r\n");
      out.write("	                  	</div>\r\n");
      out.write("	                  </div>\r\n");
      out.write("\r\n");
      out.write("                  <div class=\"my-3 text-white\">\r\n");
      out.write("                     <label class=\"form-label\">카테고리</label>\r\n");
      out.write("                     <span class=\"mx-3\">일본어, IT</span>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"my-3 text-white\">\r\n");
      out.write("                     <label class=\"form-label\">상품설명</label>\r\n");
      out.write("                     <span class=\"mx-3\">파이썬 기초강의(이엘 테그 넣기)</span>\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("                  <div id=\"reply\" class=\"text-white\">\r\n");
      out.write("                     ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("                     ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("                     <section class=\"replyList\">\r\n");
      out.write("                        <ul class=\"list-group list-group-flush\">\r\n");
      out.write("\r\n");
      out.write("                        </ul>\r\n");
      out.write("                        <script>\r\n");
      out.write("                           replyList();//헤더에서 만들 함수 호출\r\n");
      out.write("                        </script>\r\n");
      out.write("                        <!-- 댓글 수정관련 스크립트 -->\r\n");
      out.write("\r\n");
      out.write("                     </section>\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("         <!-- 리플리에 수정창 탑재 -->\r\n");
      out.write("         <div class=\"replyModal\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"modalContent\">\r\n");
      out.write("\r\n");
      out.write("               <div class=\"\">\r\n");
      out.write("                  <textarea class=\"modal_repCon form-control\" name=\"modal_repCon\"></textarea>\r\n");
      out.write("               </div>\r\n");
      out.write("\r\n");
      out.write("               <div class=\"d-flex justify-content-end my-2\">\r\n");
      out.write("                  <button type=\"button\" class=\"modal_modify_btn btn btn-success mx-2\">\r\n");
      out.write("                     수정\r\n");
      out.write("                  </button>\r\n");
      out.write("                  <button type=\"button\" class=\"modal_cancel btn btn-secondary\">\r\n");
      out.write("                     취소\r\n");
      out.write("                  </button>\r\n");
      out.write("               </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <script src=\"/resources/js/replyDelete.js\"></script>\r\n");
      out.write("            <script src=\"/resources/js/replyEdit.js\"></script>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"modalBackground\"></div><!-- 검정색 바탕에 투명도 80 -->\r\n");
      out.write("         </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("         ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/footer.jsp", out, false);
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/shop/view.jsp(55,21) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member == null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                        <p>리뷰를 남기시려면 <a href=\"/member/signin\">로그인</a>해주세요</p>\r\n");
          out.write("                     ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/shop/view.jsp(59,21) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("<!-- 로그인을 하면 댓글을 사용 -->\r\n");
          out.write("                        <section class=\"replyForm\">\r\n");
          out.write("                           <!-- 히든으로 제품번호가 들어가야됨 -->\r\n");
          out.write("                           <form role=\"form\" method=\"post\" autocomplete=\"off\">\r\n");
          out.write("\r\n");
          out.write("                              <input type=\"hidden\" name=\"gdsNum\" id=\"gdsNum\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${view.gdsNum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("                              <!-- 댓글쓰기 -->\r\n");
          out.write("                              <div class=\"my-3 text-white\">\r\n");
          out.write("                                 <textarea name=\"repCon\" id=\"repCon\"\r\n");
          out.write("                                    class=\"form-control\">리뷰를 남겨주세요</textarea>\r\n");
          out.write("                              </div>\r\n");
          out.write("\r\n");
          out.write("                              <div class=\"d-flex justify-content-end text-white\">\r\n");
          out.write("                                 <button type=\"button\" id=\"reply_btn\" class=\"btn btn-outline-primary\">\r\n");
          out.write("                                    리뷰쓰기\r\n");
          out.write("                                 </button>\r\n");
          out.write("                                 <script src=\"/resources/js/reply.js\"></script>\r\n");
          out.write("                              </div>\r\n");
          out.write("\r\n");
          out.write("                           </form>\r\n");
          out.write("                        </section>\r\n");
          out.write("                     ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }
}
