/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.69
 * Generated at: 2025-03-26 03:54:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class signup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/C:/dev/workspace/port/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/shop/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/member/../include/header.jsp", Long.valueOf(1742873470332L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1735616831101L));
    _jspx_dependants.put("jar:file:/C:/dev/workspace/port/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/shop/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!-- (1) page directive include -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("   <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("   <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("   <script src=\"https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("   <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/style.css\"/>\r\n");
      out.write("   <link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.7.0/css/all.css\" integrity=\"sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ\" crossorigin=\"anonymous\">\r\n");
      out.write("   <meta charset=\"UTF-8\">\r\n");
      out.write("   <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/ckeditor/ckeditor.js\"></script>\r\n");
      out.write("   <title>=== SHOP ===</title>\r\n");
      out.write("   <script>\r\n");
      out.write("      function replyList(){\r\n");
      out.write("         var gdsNum = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${view.gdsNum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\r\n");
      out.write("      \r\n");
      out.write("         //비동기식 데이터 요청\r\n");
      out.write("         $.getJSON(\"/shop/view/replyList\" + \"?n=\" + gdsNum, function(data){\r\n");
      out.write("            var str = \"\";//초기화\r\n");
      out.write("            $(data).each(function(){\r\n");
      out.write("               console.log(data);\r\n");
      out.write("                \r\n");
      out.write("               //날짜 데이터를 보기 쉽게 변환\r\n");
      out.write("                var repDate = new Date(this.repDate);\r\n");
      out.write("                repdate = repDate.toLocaleDateString(\"ko-KR\");\r\n");
      out.write("                \r\n");
      out.write("               //html코드 조립\r\n");
      out.write("               str += \"<li data-repNum='\" + this.repNum + \"'class='list-group-item'>\"\r\n");
      out.write("               + \"<div class=''>\"\r\n");
      out.write("               + \"<p class=''>\" + this.userName + \"</p>\"\r\n");
      out.write("               + \"<p class='mx-3'>\" + repDate + \"</p>\"\r\n");
      out.write("               + \"</div>\"\r\n");
      out.write("               + \"<div class='replyContent'>\"+this.repCon+\"</div>\"\r\n");
      out.write("               +\"");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\"\r\n");
      out.write("               +\"</li>\";\r\n");
      out.write("            });\r\n");
      out.write("             $(\"section.replyList ul\").html(str);\r\n");
      out.write("             });\r\n");
      out.write("            }\r\n");
      out.write("   </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"pt-5 bg-dark\">\r\n");
      out.write("<nav class=\"navbar navbar-expand-sm bg-dark fixed-top\">\r\n");
      out.write("   <div class=\"container-fluid\">\r\n");
      out.write("      <a class=\"navbar-brand\" href=\"/\">\r\n");
      out.write("         <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/logo2.svg\" alt=\"Logo\" width=\"50px\" height=\"50px\"/>\r\n");
      out.write("      </a>\r\n");
      out.write("      <button class=\"navbar-toggler btn-primary\" data-bs-toggle=\"collapse\" data-bs-target=\"#mynavbar\">\r\n");
      out.write("         <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("      </button>\r\n");
      out.write("      <div class=\"collapse navbar-collapse\" id=\"mynavbar\">\r\n");
      out.write("         <ul class=\"navbar-nav me-auto align-items-center\">\r\n");
      out.write("            ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("            <!-- 로그인을 했을때 -->\r\n");
      out.write("            ");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("         </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("      <form class=\"d-flex \">\r\n");
      out.write("         <div class=\"btn-group\">\r\n");
      out.write("            <input class=\"form-control\" type=\"text\" placeholder=\"Search\"/>\r\n");
      out.write("               <button class=\"btn btn-coralred\" type=\"button\">\r\n");
      out.write("                  <i class=\"fas fa-search fa-sm\"></i>\r\n");
      out.write("               </button>\r\n");
      out.write("         </div>\r\n");
      out.write("      </form>\r\n");
      out.write("   </div>\r\n");
      out.write("</nav>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/daum.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container-fixed bg-dark\">\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("	<div class=\"row justify-content-center\">\r\n");
      out.write("		<div class=\"col-lg-12\">\r\n");
      out.write("			<div class=\"card o-hidden border-0 shadow-lg my-5\">\r\n");
      out.write("				<div class=\"card-body p-0\">\r\n");
      out.write("					<div class=\"row\">\r\n");
      out.write("						<div class=\"px-3 col-lg-6 d-none d-lg-block bg-login-image bg-dark\">\r\n");
      out.write("                        <!--배경이미지-->\r\n");
      out.write("                        </div>\r\n");
      out.write("						<div class=\"col-lg-6\">\r\n");
      out.write("							<div class=\"p-5\">\r\n");
      out.write("								<div class=\"text-center\">\r\n");
      out.write("									<h1 class=\"text-dark\">会員登録</h1>\r\n");
      out.write("									<h1 class=\"h4 text-gray-900 mb-4\">Join Membership</h1>\r\n");
      out.write("									<form method=\"post\" class=\"was-validated\">\r\n");
      out.write("										<div class=\"mb-4\">\r\n");
      out.write("											<input\r\n");
      out.write("											type=\"text\"\r\n");
      out.write("											name=\"userId\"\r\n");
      out.write("											class=\"form-control-user userIdIcon\"\r\n");
      out.write("											required=\"required\"\r\n");
      out.write("											/>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"mb-2\">\r\n");
      out.write("											<input\r\n");
      out.write("											type=\"password\"\r\n");
      out.write("											name=\"userPass\"\r\n");
      out.write("											class=\"form-control-user userPassIcon\"\r\n");
      out.write("											required=\"required\"\r\n");
      out.write("											/>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"mb-4\">\r\n");
      out.write("											<input\r\n");
      out.write("											type=\"password\"\r\n");
      out.write("											name=\"userPassRe\"\r\n");
      out.write("											class=\"form-control-user userPassReIcon\"\r\n");
      out.write("											required=\"required\"\r\n");
      out.write("											/>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"mb-4\">\r\n");
      out.write("											<div class=\"btn-group\">\r\n");
      out.write("												<label class=\"btn border-0\">\r\n");
      out.write("													<input type=\"radio\" name=\"userGender\" value=\"男\" autocomplete=\"off\" checked>男 (Male)\r\n");
      out.write("												</label>\r\n");
      out.write("												<label class=\"btn border-0\">\r\n");
      out.write("													<input type=\"radio\" name=\"userGender\" value=\"女\" autocomplete=\"off\">女 (Female)\r\n");
      out.write("												</label>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"mb-2\">\r\n");
      out.write("											<input\r\n");
      out.write("											type=\"text\"\r\n");
      out.write("											name=\"userName\"\r\n");
      out.write("											class=\"form-control-user userNameIcon\"\r\n");
      out.write("											required=\"required\"\r\n");
      out.write("											/>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"mb-2\">\r\n");
      out.write("											<input\r\n");
      out.write("											type=\"text\"\r\n");
      out.write("											name=\"userEmail\"\r\n");
      out.write("											class=\"form-control-user userEmailIcon\"\r\n");
      out.write("											required=\"required\"\r\n");
      out.write("											/>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"mb-4\">\r\n");
      out.write("											<input\r\n");
      out.write("											type=\"text\"\r\n");
      out.write("											name=\"userPhone\"\r\n");
      out.write("											class=\"form-control-user userPhoneIcon\"\r\n");
      out.write("											required=\"required\"\r\n");
      out.write("											/>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"mb-2\">\r\n");
      out.write("											<label class=\"form-label text-dark\">アドレス <small class=\"text-dark\">address</small></label>\r\n");
      out.write("											<div class=\"d-flex\">\r\n");
      out.write("												<input\r\n");
      out.write("												type=\"text\"\r\n");
      out.write("												placeholder=\"search the address\"\r\n");
      out.write("												name=\"userAddr1\"\r\n");
      out.write("												readonly=\"readonly\"\r\n");
      out.write("												class=\"form-control form-control-user address_input_1 w-75\"\r\n");
      out.write("												/>\r\n");
      out.write("												<a class=\"btn btn-outline-primary border-radius-top-right-sm w-25\" onclick=\"go_daum_address()\">住所検索</a>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"mb-2\">\r\n");
      out.write("											<input\r\n");
      out.write("											type=\"text\"\r\n");
      out.write("											placeholder=\"\"\r\n");
      out.write("											name=\"userAddr2\"\r\n");
      out.write("											readonly=\"readonly\"\r\n");
      out.write("											class=\"form-control form-control-user address_input_2\"\r\n");
      out.write("											/>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"mb-4\">\r\n");
      out.write("											<input\r\n");
      out.write("											type=\"text\"\r\n");
      out.write("											placeholder=\"\"\r\n");
      out.write("											name=\"userAddr3\"\r\n");
      out.write("											readonly=\"readonly\"\r\n");
      out.write("											class=\"form-control form-control-user address_input_3\"\r\n");
      out.write("											/>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"my-3\">\r\n");
      out.write("											<input\r\n");
      out.write("											type=\"submit\"\r\n");
      out.write("											class=\"btn btn-primary btn-user btn-block\"\r\n");
      out.write("											value=\"Join Membership\"\r\n");
      out.write("											/>\r\n");
      out.write("										</div>\r\n");
      out.write("										<p class=\"mb-3\">\r\n");
      out.write("	                                    	<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/google\" class=\"btn btn-google btn-user btn-block\">\r\n");
      out.write("	                                    		<i class=\"fab fa-google fa-fw\"></i>\r\n");
      out.write("	                                    		&nbsp;Join with Google\r\n");
      out.write("	                                    	</a>\r\n");
      out.write("	                                    </p>\r\n");
      out.write("	                                    <p class=\"mb-3\">\r\n");
      out.write("	                                    	<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/face\" class=\"btn btn-facebook btn-user btn-block\">\r\n");
      out.write("	                                    		<i class=\"fab fa-facebook fa-fw\"></i>\r\n");
      out.write("	                                    		&nbsp;Join with Facebook\r\n");
      out.write("	                                    	</a>\r\n");
      out.write("	                                    </p>	\r\n");
      out.write("										<div class=\"mb-3\">\r\n");
      out.write("											<a class=\"small text-dark\" href=\"/member/forgot.jsp\">Forgot Password?</a>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"mb-3\">\r\n");
      out.write("											<a class=\"small text-dark\" href=\"/member/login.jsp\">Already have an account? login!</a>\r\n");
      out.write("										</div>\r\n");
      out.write("									</form>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- (2) jsp include -->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/footer.jsp", out, false);
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/member/../include/header.jsp(5,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("contextPath");
      // /WEB-INF/views/member/../include/header.jsp(5,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/member/../include/header.jsp(5,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/member/../include/header.jsp(38,17) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\"//세션이 있어야만 수정삭제가 가능\r\n");
          out.write("               + \"<div class='replyFooter my-3'>\"\r\n");
          out.write("               + \"<button type='button' class='modify btn btn-secondary' data-repNum='\"+this.repNum+\"'>M</button>\"\r\n");
          out.write("               + \"<button type='button' class='delete btn btn-secondary mx-3' data-repNum='\"+this.repNum+\"'>D</button>\"\r\n");
          out.write("               + \"</div>\"\r\n");
          out.write("               +\"");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/member/../include/header.jsp(62,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member == null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("<!-- 미로그인 -->\r\n");
          out.write("               <li class=\"nav-item\">\r\n");
          out.write("                  <a class=\"nav-link link-coralred\" href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/signin\">Login</a>\r\n");
          out.write("               </li>\r\n");
          out.write("               <li class=\"nav-item mx-3\">\r\n");
          out.write("                  <a class=\"nav-link link-coralred\" href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/signup\">Join</a>\r\n");
          out.write("               </li>\r\n");
          out.write("               <li class=\"nav-item\">\r\n");
          out.write("                  <a class=\"text-decoration-none link-coralred\" href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/shop/list?c=101&l=2\">Contents</a>\r\n");
          out.write("               </li>\r\n");
          out.write("            ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /WEB-INF/views/member/../include/header.jsp(74,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member != null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                <li class=\"nav-item mx-2\">\r\n");
          out.write("                    <span class=\"fw-bold text-white\">\r\n");
          out.write("                    ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.userName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\r\n");
          out.write("                    </span>\r\n");
          out.write("                </li>\r\n");
          out.write("         \r\n");
          out.write("                 <div class=\"topbar-divider d-none d-sm-block\"></div>\r\n");
          out.write("              \r\n");
          out.write("               <li class=\"nav-item fw-bold mx-2\">\r\n");
          out.write("                  <a class=\"nav-link fw-bold link-coralred\" href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/shop/list?c=1&l=2\">Contents</a>\r\n");
          out.write("               </li>\r\n");
          out.write("               <li class=\"nav-item fw-bold mx-2\">\r\n");
          out.write("                  <a class=\"nav-link link-coralred\" href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/shop/cartList\">Scrap</a>\r\n");
          out.write("               </li>\r\n");
          out.write("               <li class=\"nav-item fw-bold mx-3\">\r\n");
          out.write("                  <a class=\"nav-link small link-coralred\" href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/signout\">Logout</a>\r\n");
          out.write("               </li>\r\n");
          out.write("         \r\n");
          out.write("                 <!-- 로그인을 했는데 관리자라면 -->\r\n");
          out.write("               ");
          if (_jspx_meth_c_005fif_005f3(_jspx_th_c_005fif_005f2, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("            ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f2);
      // /WEB-INF/views/member/../include/header.jsp(94,15) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.verify == 9 }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                  <a class=\"nav-link mx-3 text-white\" href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/admin/index\">Go to Admin Page</a>\r\n");
          out.write("               ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }
}
